### ISSUE TITLE
Checking circuits needs improvements

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1706]
Currently:

1.  When opening an activity to view, the user immediately sees pop-up messages that checking circuits is important. If the activity has multiple steps with different circuits, there will be multiple messages. They look identical, so the user has to tap many times. These messages are not needed at all... What was the logic for showing them, @jafarigit ?
2. Checking the circuit does not always work as expected (video sent to @jafarigit ). 
How to reproduce: 
1. When editing a step, add and connect 4 bits. Add one more bit and not connect it.
2. Open the activity in Play mode. Connect 4 bits exactly as in edit mode.
3. Observe that there is no message about a successful circuit.
4. Connect the fifth bit to the circuit (this is NOT how it is in the Edit mode).
5. Observe the successful circuit pop up message.

It should be possible to connect some bits, and leave some other bits disconnected in the edit mode. And in Play mode, this configuration should be successful.

**Comment by jafarigit** [comment]
Done

**Comment by fominykh** [comment]
Testing the build. The issue is still present. 

In edit mode,
1. I add two steps.
2. in step 1, I add 5 bits. I connect 4 of them.
3. in step 2, I add 2 bits. I connect them.

In Play mode, 
4. I see on step 1 all bits disconnected. As expected.
5. I tap on one of the bits. And immediately see a popup that the circuit is connected correctly. None of the bits are actually connected.
6. I move one of the bits. And I see the second pop-up that the circuit is connected correctly.
7. I connect the bits correctly. And I do not see a pop-up.
8. I go to step 2. Connect the 2 bits. And I do not see a pop-up.
